### ISSUE TITLE
http version

### ISSUE THREAD

**Issue by ArivAfonso** [rIIh/oxford-dictionary-dart#2]
Hey! Can you please change the http dependency to 13.0.0? I am building an app that requires the googleapis package which has http 13.0.0 dependency.

**Comment by melvspace** [comment]
Hi! Currently working on null-safe version. Will try to deliver update asap.

**Comment by melvspace** [comment]
Hi! I uploaded 2.0.2 version in pub.dev. Feel free to check it. But keep in mind, package uses `json_serializable` and after migration to null-safety there can be Null Cast errors. If you encounter one, please let me know by opening an issue.

**Comment by ArivAfonso** [comment]
Thanks for solving the problem
